name: CI
on:
  push:
    branches: [ ecx-v1.31.0 ]
env:
  BASEIMAGE: k8s.gcr.io/debian-base-amd64:v2.0.0
  labels: ${{ github.ref_name }}
  label: "${labels:4:10}"
  TAG: "${${{ github.ref_name }}#ecx-}"

jobs:
  build-4:
    runs-on: 
      group: Default
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run a multi-line script
        run: |
          echo ${{ env.TAG }}
