name: CI
on:
  push:
    branches: [ ecx-v1.31.0 ]

jobs:
  build-3:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          docker ps
          go version
