name: CI
on:
  push:
    branches: [ ecx-v1.31.0 ]

jobs:
  build-4:
    runs-on: 
      group: Default
    steps:
      - name: Run a multi-line script
        run: |
          echo ${{ github.ref_name#ecx- }}
          echo ${{ github.ref_name }}
