name: CI
on:
  push:
    branches: [ ecx-v1.31.0 ]

jobs:
  build-4:
    runs-on: 
      group: Default
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run a multi-line script
        run: |
          echo ${{ github.ref }}
          docker ps
          go version
