name: CI
on:
  push:
    branches: [ ecx-v1.31.0 ]
env:
  BASEIMAGE: k8s.gcr.io/debian-base-amd64:v2.0.0
  labels: ${{ github.ref_name }}
  label: "${labels:4:10}"
  TAG: $labels[4]

jobs:
  build-4:
    runs-on: 
      group: Default
    steps:
      - name: Run a multi-line script
        run: |
          echo ${{ env.TAG }}
          str="Hello, World!"
          substr="${str:6:5}"  # 从索引 6 开始截取 5 个字符
          echo "$substr"
